### ISSUE TITLE
Tanker altitude is far too high for A10s to use

### ISSUE THREAD

**Issue by AlphaLima85** [Hoggit/TNN#5] opened 2017-04-05 03:53 UTC
IIRC we use to put them around 150 maybe up to 180 or 200 but even that is getting pretty high for an A10. Perhaps duplicate the current one and offset it lower?

**Comment by Lugghawk** [comment] 2017-04-05 03:56
Duplicate of #1

**Closed by Lugghawk** 2017-04-05 03:56 UTC
